# Generated by Django 3.0.2 on 2020-11-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('phone', models.IntegerField()),
                ('job', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rule', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
                ('date_join', models.DateField()),
                ('date_out', models.DateField()),
                ('out_desc', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Members')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('kecamatan', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Members')),
            ],
        ),
    ]
